dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'

    // JWT (валидация токенов)
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.testcontainers:junit-jupiter:1.20.4'
    testImplementation 'org.testcontainers:postgresql:1.20.4'
}

openApiGenerate {
    generatorName.set('spring')
    inputSpec.set("$rootDir/openapi/notification-service.yaml")
    outputDir.set("${layout.buildDirectory.get()}/generated")
    apiPackage.set('com.taxi.notification.api')
    modelPackage.set('com.taxi.notification.dto')
    invokerPackage.set('com.taxi.notification.invoker')
    configOptions.set([
        interfaceOnly       : 'true',
        useSpringBoot3      : 'true',
        useTags             : 'true',
        dateLibrary         : 'java8',
        serializationLibrary: 'jackson',
        useJakartaEe        : 'true',
        skipDefaultInterface: 'true'
    ])
}
